services:
  app_mvc_sqlserver:
    container_name: app-mvc-sqlserver
    image: app-mvc-sqlserver
    build:
      context: ./.docker/sqlserver
      dockerfile: Dockerfile
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: yourStrong(!)Password
    ports:
      - 1433:1433
    volumes:
      - sqlserver_app_mvc:/var/opt/mssql/data

volumes:
  sqlserver_app_mvc:
